In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plp

In [4]:
df=pd.read_csv("J:\data_cleaned.csv")
df.head()

   Survived   Age     Fare  ...  Embarked_C  Embarked_Q  Embarked_S
0         0  22.0   7.2500  ...           0           0           1
1         1  38.0  71.2833  ...           1           0           0
2         1  26.0   7.9250  ...           0           0           1
3         1  35.0  53.1000  ...           0           0           1
4         0  35.0   8.0500  ...           0           0           1

[5 rows x 25 columns]

In [5]:
df.corr() #statistical Method

            Survived           Age  ...  Embarked_Q  Embarked_S
Survived    1.000000 -6.980852e-02  ...    0.003650   -0.149683
Age        -0.069809  1.000000e+00  ...   -0.013855   -0.019336
Fare        0.257307  9.156609e-02  ...   -0.117216   -0.162184
Pclass_1    0.285904  3.199164e-01  ...   -0.155342   -0.161921
Pclass_2    0.093349  6.589145e-03  ...   -0.127301    0.189980
Pclass_3   -0.322308 -2.810040e-01  ...    0.237449   -0.015104
Sex_female  0.543351 -8.415344e-02  ...    0.074115   -0.119224
Sex_male   -0.543351  8.415344e-02  ...   -0.074115    0.119224
SibSp_0    -0.115867  1.484087e-01  ...    0.055398   -0.004412
SibSp_1     0.173076  1.457006e-02  ...   -0.066568   -0.038742
SibSp_2     0.029796 -8.761287e-02  ...    0.013285   -0.018741
SibSp_3    -0.037215 -1.231756e-01  ...   -0.041590    0.083277
SibSp_4    -0.064123 -2.502114e-01  ...    0.069400    0.016964
SibSp_5    -0.059292 -1.127240e-01  ...   -0.023105    0.046263
SibSp_8    -0.070234  2.240073e-18  ...   -0.027369    0.054801
Parch_0    -0.147408  2.615834e-01  ...    0.097467   -0.032821
Parch_1     0.134174 -1.479081e-01  ...   -0.049463   -0.026350
Parch_2     0.075020 -2.564354e-01  ...   -0.082626    0.061529
Parch_3     0.033391  2.023852e-02  ...   -0.023105    0.012614
Parch_4    -0.053002  7.648724e-02  ...   -0.020654    0.041356
Parch_5    -0.028398  5.492439e-02  ...    0.030366    0.012614
Parch_6    -0.026456  3.430983e-02  ...   -0.010310    0.020643
Embarked_C  0.168240  3.202442e-02  ...   -0.148258   -0.782742
Embarked_Q  0.003650 -1.385524e-02  ...    1.000000   -0.499421
Embarked_S -0.149683 -1.933560e-02  ...   -0.499421    1.000000

[25 rows x 25 columns]

In [6]:
x=df.drop(['Survived','Fare','Pclass_1','Pclass_3','Sex_female','Sex_male'],axis=1)
y=df['Survived']

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.4,random_state=30)

In [8]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((356, 19), (535, 19), (356,), (535,))

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [10]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

Predicting the test results for random forest

In [11]:
y_pred=rf.predict(x_test)
y_pred1=dt.predict(x_test)

In [12]:
cal=pd.DataFrame(np.c_[y_test,y_pred],columns=["Original","Predicted"])
cal

     Original  Predicted
0           1          1
1           1          0
2           0          0
3           1          0
4           0          1
..        ...        ...
530         0          0
531         0          0
532         0          1
533         1          1
534         1          0

[535 rows x 2 columns]

In [13]:
from sklearn.metrics import accuracy_score

In [14]:
accuracy_score=accuracy_score(y_test,y_pred)

In [15]:
accuracy_score # For random forest

0.6242990654205608

In [16]:
from sklearn.metrics import accuracy_score   # For Decision Tree
accuracy_score=accuracy_score(y_test,y_pred1)
accuracy_score

0.6149532710280374

In [17]:
from sklearn.metrics import accuracy_score,classification_report

In [ ]:
classification=classification_report(y_test,y_pred)   # Random forest
print(classification)

              precision    recall  f1-score   support

           0       0.68      0.75      0.71       332
           1       0.51      0.42      0.46       203

    accuracy                           0.62       535
   macro avg       0.59      0.58      0.59       535
weighted avg       0.61      0.62      0.62       535

In [ ]:
cs=classification_report(y_test,y_pred1)   # Decision Tree
print(cs)

              precision    recall  f1-score   support

           0       0.67      0.74      0.71       332
           1       0.49      0.40      0.44       203

    accuracy                           0.61       535
   macro avg       0.58      0.57      0.57       535
weighted avg       0.60      0.61      0.61       535