In [51]:
pip install numpy

Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [52]:
pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [53]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (2.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (3.9.4)
Requirement already satisfied: pandas>=1.2 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (2.3.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.0)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [54]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [55]:
df=pd.read_csv("J:\Social_Network_Ads.csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [56]:
df.corr

<bound method DataFrame.corr of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [57]:
x=df.drop(['Purchased','User ID','Gender'],axis=1) # Independent columns
y=df['Purchased']  # Dependent column

In [58]:
x.shape,y.shape

((400, 2), (400,))

In [59]:
print(x_train)

     Age  EstimatedSalary
313   49           141000
21    47            49000
222   37           144000
350   38           113000
398   36            33000
..   ...              ...
309   38            50000
386   49            39000
140   19            85000
301   48            74000
293   37            77000

[320 rows x 2 columns]

In [60]:
print(x_test)

     Age  EstimatedSalary
35    35            27000
316   54           104000
281   35            61000
74    32            18000
296   42            73000
..   ...              ...
188   35            72000
245   51           146000
118   40            59000
272   60            42000
365   59            29000

[80 rows x 2 columns]

In [61]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=30) # The random state will take random values in the rows based on the random number and  remain same also unchanged

In [62]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((320, 2), (80, 2), (320,), (80,))

In [63]:
classifier=LogisticRegression()
classifier.fit(x_train,y_train)

LogisticRegression()

Predicting the test results for logistic regression

In [64]:
y_pred=classifier.predict(x_test)

In [65]:

calculation = pd.DataFrame(np.c_[y_test, y_pred], columns=["Original Message", "Predicted"])
calculation    # DataFrame is used to give structured data

    Original Message  Predicted
0                  0          0
1                  1          1
2                  0          0
3                  0          0
4                  1          0
..               ...        ...
75                 0          0
76                 1          1
77                 0          0
78                 1          1
79                 1          1

[80 rows x 2 columns]

In [66]:
from sklearn.metrics import accuracy_score

In [67]:
accuracy_score=accuracy_score(y_test,y_pred)

In [72]:
print("Accuracy score for test data is: "+str(accuracy_score))

Accuracy score for test data is: 0.8625

In [73]:
from sklearn.metrics import accuracy_score,classification_report

In [74]:
accuracy_score=accuracy_score(y_test,y_pred)

In [78]:
classification=classification_report(y_test,y_pred)
print(classification)

              precision    recall  f1-score   support

           0       0.82      1.00      0.90        49
           1       1.00      0.65      0.78        31

    accuracy                           0.86        80
   macro avg       0.91      0.82      0.84        80
weighted avg       0.89      0.86      0.85        80