In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plp

In [15]:
df=pd.read_csv("J:\Salary_Data.csv")
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [18]:
df.corr()

                 YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [20]:
x=df.drop(['Salary'],axis=1)
y=df['Salary']

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.3,random_state=30)

In [22]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((9, 1), (21, 1), (9,), (21,))

In [32]:
from sklearn.linear_model import LogisticRegression
LogisticRegression=LogisticRegression()
LogisticRegression.fit(x_train,y_train)

c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Predicting the test results for linear regression

In [36]:
y_pred=LogisticRegression.predict(x_test)

In [37]:
result=pd.DataFrame(np.c_[y_test,y_pred],columns=["Original","Predicted"])
result

    Original  Predicted
0      67938      57081
1     122391     121872
2     116969     121872
3      63218      56642
4     109431     112635
5      39343      37731
6      64445      56642
7      60150      37731
8     105582     112635
9      39891      37731
10     55794      56957
11    101302     113812
12     81363      91738
13     93940      91738
14     46205      37731
15     66029      57081
16     54445      56642
17     57189      56642
18     43525      37731
19     61111      57081
20     83088      57081

In [38]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
acc

0.0

In [39]:
from sklearn.metrics import accuracy_score,classification_report
cs=classification_report(y_test,y_pred)
print(cs)

              precision    recall  f1-score   support

       37731       0.00      0.00      0.00       0.0
       39343       0.00      0.00      0.00       1.0
       39891       0.00      0.00      0.00       1.0
       43525       0.00      0.00      0.00       1.0
       46205       0.00      0.00      0.00       1.0
       54445       0.00      0.00      0.00       1.0
       55794       0.00      0.00      0.00       1.0
       56642       0.00      0.00      0.00       0.0
       56957       0.00      0.00      0.00       0.0
       57081       0.00      0.00      0.00       0.0
       57189       0.00      0.00      0.00       1.0
       60150       0.00      0.00      0.00       1.0
       61111       0.00      0.00      0.00       1.0
       63218       0.00      0.00      0.00       1.0
       64445       0.00      0.00      0.00       1.0
       66029       0.00      0.00      0.00       1.0
       67938       0.00      0.00      0.00       1.0
       81363       0.00      0.00      0.00       1.0
       83088       0.00      0.00      0.00       1.0
       91738       0.00      0.00      0.00       0.0
       93940       0.00      0.00      0.00       1.0
      101302       0.00      0.00      0.00       1.0
      105582       0.00      0.00      0.00       1.0
      109431       0.00      0.00      0.00       1.0
      112635       0.00      0.00      0.00       0.0
      113812       0.00      0.00      0.00       0.0
      116969       0.00      0.00      0.00       1.0
      121872       0.00      0.00      0.00       0.0
      122391       0.00      0.00      0.00       1.0

    accuracy                           0.00      21.0
   macro avg       0.00      0.00      0.00      21.0
weighted avg       0.00      0.00      0.00      21.0

c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))